// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Zarasa.Editorial.Api.Data;
using Zarasa.Editorial.Api.Models;

namespace Zarasa.Editorial.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171106191532_admin_email_added_to_journal")]
    partial class admin_email_added_to_journal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Zarasa.Editorial.Api.Models.Journal", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("admin_email")
                        .HasMaxLength(100);

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<DateTime>("created_at");

                    b.Property<long?>("created_by");

                    b.Property<string>("detail")
                        .HasMaxLength(2000);

                    b.Property<bool>("is_deleted");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("organization_name")
                        .HasMaxLength(100);

                    b.Property<int>("status");

                    b.Property<DateTime>("updated_at");

                    b.Property<long?>("updated_by");

                    b.HasKey("id");

                    b.ToTable("journals");
                });

            modelBuilder.Entity("Zarasa.Editorial.Api.Models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("created_at");

                    b.Property<long?>("created_by");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<bool>("is_active");

                    b.Property<bool>("is_deleted");

                    b.Property<long?>("journal_id");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("salt");

                    b.Property<DateTime>("updated_at");

                    b.Property<long?>("updated_by");

                    b.Property<int>("user_type");

                    b.HasKey("id");

                    b.HasIndex("journal_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Zarasa.Editorial.Api.Models.User", b =>
                {
                    b.HasOne("Zarasa.Editorial.Api.Models.Journal", "journal")
                        .WithMany("users")
                        .HasForeignKey("journal_id");
                });
#pragma warning restore 612, 618
        }
    }
}
